### ISSUE TITLE
User needs blueprint_id for provisioning

### ISSUE THREAD

**Issue by cferber** [vmware/terraform-provider-vra#104]
Where does a user get blueprint_id from? It's not listed in the GUI, the only way I am aware is getting it through VCS-CLI or API. 
Why don't we support blueprint_name as parameter?

**Comment by dmettem** [comment]
Data source for vra_blueprint is under works and it will give the ability to get the blueprint id from blueprint name, which can be mapped to vra_deployment resource.
For now, one can get the blueprint id even from UI from the address bar when the blueprint is opened for edit.

**Comment by cars** [comment]
If you have access to cloud assembly (at least on prem) you can pull the blueprint id from the url...
![vra8_bp_id](https://user-images.githubusercontent.com/137110/68795206-59d5ac00-0605-11ea-9993-5255c21c149e.png)

so I see a URL such as: https://vra8.example.com/automation-ui/#/blueprint-ui;ash=%2Fblueprint%2Fedit%2F5326aa2b-fae1-472d-b22b-04365738d392

in this case the blueprint id is: 5326aa2b-fae1-472d-b22b-04365738d392

If you don't have access (i.e. just service broker access). I'm not sure there is a way yet to get it... 
I'd suspect that since there looks to be plumbing in the vRA SDK (https://github.com/vmware/vra-sdk-go/blob/master/pkg/models/blueprint.go) and deployments just got added a week or so ago that maybe blueprints are coming as both a resource and data source... but would look to @markpeek for validation....

**Comment by mdittbrenner215** [comment]
Or use postman

{{url-home}}/blueprint/api/blueprints

https://github.com/vaficionado/cas-apis

**Comment by mdittbrenner215** [comment]
This will actually be important if a person has more than 1 VRA and exports and imports blueprints.  The ID does not stay the same it seems like vra 7.x . The ability to call by name is alot easier as you can have the same name in multiple vra's.

**Comment by mdittbrenner215** [comment]
Looks for this we would need to do a data resource that calls /blueprint/api/blueprints filter by name.
Take that info in variable and use ID that is returned from the  data resource to call blueprint request since request can only use ID and not name.

**Comment by dmettem** [comment]
Fixed in #129.

**Comment by dmettem** [comment]
Released in [0.1.6](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.6).
