### ISSUE TITLE
There should be a way to create a single deployment object with multiple resources 

### ISSUE THREAD

**Issue by sbadem** [vmware/terraform-provider-vra#113]
Each resource creates a separate deployment in vRA which  may be difficult to manage.

**Comment by AnjaliMangal** [comment]
This is a feature enhancement , we will pick it up in ongoing sprint and have it early next week .

**Comment by dmettem** [comment]
A deployment getting created for each resource (machine, network, block device, and load balancer) is fairly a new feature in vRA Cloud and I guess will be part of 8.0.1 when it comes out. We will adding the support for letting the user provide the deployment id created from one resource in other resources so that all resources created from a terraform config file can be managed under a single deployment.

**Comment by Prativa20** [comment]
Fixed as part of #117. Added an example https://github.com/vmware/terraform-provider-vra/tree/master/examples/multiple_resources_deployment
