### ISSUE TITLE
Creating a resource with deployment ID of a pre-created deployment doesn't associate the machines with the deployment

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#120]
I created an empty deployment through UI (ID: bd18dfd2-3ad1-4e01-814d-4c87c899235b) in vRA8, And created two machines using terraform provider 

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terrafrom test machine"
  project_id  = data.vra_project.this.id
  deployment_id = "bd18dfd2-3ad1-4e01-814d-4c87c899235b"
  name        = "tf-machine"
  image       = "ubuntu"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  timeouts {
        create = "20m"
  }
}

The machines got provisioned successfully however the machines didn't get associated to the pre-created deployment. When I checked the machine document by doing the GET call, I noticed that the machine customProperties is missing "__deployment_id": attribute.

**Comment by Prativa20** [comment]
Tested it directly through iaas apis. The machine does not return a deployment id. This looks like a product issue

**Comment by mdittbrenner215** [comment]
I don’t think it’s a product issue. It’s a different way in vra 8 vs vra 7.  Vra 7 only had deployments. Vra 8 has IaaS which is more cloud like and doesn’t do the deployments. There is a deployment api that can be used in vra 8

**Comment by Prativa20** [comment]
@mdittbrenner215 In vra8, when you create a machine, network, LB or a block device through iaas apis, a deployment is created. This is working fine in vra cloud. The same should happen in vra8. 
Here is an example for that https://github.com/vmware/terraform-provider-vra/tree/master/examples/multiple_resources_deployment
A block device is created which internally creates a deployment and that deployment id is being used to create more resources like machine, so that all these resources end up in the same deployment. This was done in the provider as part of https://github.com/vmware/terraform-provider-vra/issues/113

**Comment by pmamtora** [comment]
Created a product bug: https://jira.eng.vmware.com/browse/VCOM-14386

**Comment by dmettem** [comment]
The functionality to associate new resources (machine, disk, network and load balancer) currently works only on vRA Cloud.  As the corresponding product changes make it into vRA 8.x, this functionality will work on vRA on-prem product too.
I'm marking this as vra8 only issue and we will update ETA and the vRA product release version once we finalize.

**Comment by vrabbi** [comment]
this has been fixed in vra 8.1 and is now working as per my tests.

**Comment by dmettem** [comment]
Thanks @vrabbi for checking on 8.1. and confirming here.
@pmamtora - Closing the issue as this feature rolled out with 8.1 and also should work on vRA Cloud.
