### ISSUE TITLE
Updating the machine image that is attached to disk results in 404

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#131]
I created a machine that is attached to disk using

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terraform vra_machine"
  project_id  = data.vra_project.this.id
  name        = "Terraform_Provider-002"
  image       = "centos"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  disks {
      block_device_id = vra_block_device.disk3[1].id
  }

  timeouts {
        create = "20m"
  }
}

resource "vra_block_device" "disk3" {
  capacity_in_gb = 10
  count = 2
  name = "terraform_vra_block_device_102"
  project_id = data.vra_project.this.id
}

In the second iteration, I changed the image to ubuntu

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terraform vra_machine"
  project_id  = data.vra_project.this.id
  name        = "Terraform_Provider-002"
  image       = "ubuntu"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  disks {
      block_device_id = vra_block_device.disk3[1].id
  }

  timeouts {
        create = "20m"
  }
}

resource "vra_block_device" "disk3" {
  capacity_in_gb = 10
  count = 2
  name = "terraform_vra_block_device_102"
  project_id = data.vra_project.this.id
}

The second iteration fails with 404. 
I think when it tries to recreate a machine, the disk gets deleted when machine is deleted and the newly recreated machine is look for the disk to attach to

**Comment by pmamtora** [comment]
NOTE: the update of machine image without disk works fine

**Comment by dmettem** [comment]
@pmamtora - As per the product behavior, the disk gets deleted by default when the machine to which it is attached to is deleted. If the expectation for the disk to stay even after the machine to which the disk is attached to, we may use `persistent` flag in block_device properties. Let me know if that suffices the ask here.

**Comment by pmamtora** [comment]
@dmettem the use case here is updating the image, we see two different behavior. Let me summarize my previous comments 
1) Update the image of a machine that does not have any attached disk -> works fine
2) Update the image of a machine that has attached disk -> throws 404

**Comment by dmettem** [comment]
@pmamtora As mentioned in my last comment, updates to `image` and `image_ref` forces the delete of existing machine and creates a new machine. As per vRA product behavior, a disk attached to a machine gets deleted by default unless the disk itself has the `persistent` flag set to `true`. Hence the 404 error while trying to attach the delete disk (because the `persistent` is `false`) to newly provisioned machine.

Terraform being declarative language, if the disk needs to be persisted and connected to new machine as the image is updated in the machine resource, the disk itself has to be provisioned with `persistent` set to `true`. If there is no requirement to persist the disk between the recreates of machine, the disk also has to be recreated with machine.
