### ISSUE TITLE
Pass underlying vRA error to Terraform

### ISSUE THREAD

**Issue by dark2phoenix** [vmware/terraform-provider-vra#156]
On the vRA side, I can see the error, whether it is running out of IP addresses, or the network profile specified in the Terraform plan cannot be found on vRA side, etc., but from end user point of view, the command only returned failure, without any specific information.   

Is it possible to send the actual vRA error back to the user as a return from the apply?

**Comment by dmettem** [comment]
@dark2phoenix - Will you please provide the specifics of the resources/data sources that you noticed this with?

**Comment by dark2phoenix** [comment]
So in our test environment, we only have 7 available IP's to use (IP Addressing is being managed by vRA Network Profiles).  So we can reproduce this by trying to deploy 8 VM's - it dies on the 8th VM because there are no IP's left.

**Comment by dark2phoenix** [comment]
SO we verified this happens when vRA runs out of IP's to when provisioning a VM.  To test this easily, we created a /31 in NSX-T and then create a blueprint that deploys 2 VMs.   Is that specific enough for your needs, or is there some additional information we can provide?

**Comment by mdittbrenner215** [comment]
In one case i used all of the ip addresses and this is the error terraform shows.

020/02/20 19:03:15 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: [GET /deployment/api/deployments/{depId}][200] getDeploymentByIdUsingGETOK  &{BlueprintID:38896c13-a57a-4c58-a5dd-ff66ce7f4f2b BlueprintVersion: CatalogItemID: CatalogItemVersion: CreatedAt:2020-02-20T22:07:32.605Z CreatedBy:mdittb638 Description: Expense:<nil> IconID: ID:7ca7540b-b5fc-4a32-a6d1-141f7cb17f9d Inputs:map[inCMI:Cloud-init inCount:75 inFlavor:4cpu-16Gb inITRC:test123 inIpv:IPv6 inLicense:rhat inRail:public inTags:mike:new inTenant:OneCloud vmName:md-demo1] LastRequest:0xc0006290e0 LastUpdatedAt:2020-02-21T00:01:44.744Z LastUpdatedBy:tango-blueprint-FXQgOCfpgDDR8tET LeaseExpireAt:0001-01-01T00:00:00.000Z Name:0xc00060a5a0 OrgID:9032098a-52e4-49a1-aa35-3eb11845413e Project:<nil> ProjectID:9683a1f4-2f27-424a-bf4b-09e41d9a4bcd Resources:[] Status:UPDATE_FAILED}
2020/02/20 19:03:15 [ERROR] <root>: eval: *terraform.EvalSequence, err: [GET /deployment/api/deployments/{depId}][200] getDeploymentByIdUsingGETOK  &{BlueprintID:38896c13-a57a-4c58-a5dd-ff66ce7f4f2b BlueprintVersion: CatalogItemID: CatalogItemVersion: CreatedAt:2020-02-20T22:07:32.605Z CreatedBy:mdittb638 Description: Expense:<nil> IconID: ID:7ca7540b-b5fc-4a32-a6d1-141f7cb17f9d Inputs:map[inCMI:Cloud-init inCount:75 inFlavor:4cpu-16Gb inITRC:test123 inIpv:IPv6 inLicense:rhat inRail:public inTags:mike:new inTenant:OneCloud vmName:md-demo1] LastRequest:0xc0006290e0 LastUpdatedAt:2020-02-21T00:01:44.744Z LastUpdatedBy:tango-blueprint-FXQgOCfpgDDR8tET LeaseExpireAt:0001-01-01T00:00:00.000Z Name:0xc00060a5a0 OrgID:9032098a-52e4-49a1-aa35-3eb11845413e Project:<nil> ProjectID:9683a1f4-2f27-424a-bf4b-09e41d9a4bcd Resources:[] Status:UPDATE_FAILED}
2020/02/20 19:03:15 [TRACE] [walkApply] Exiting eval tree: vra_deployment.this
2020/02/20 19:03:15 [TRACE] vertex "vra_deployment.this": visit complete
2020/02/20 19:03:15 [TRACE] dag/walk: upstream of "provider.vra (close)" errored, so skipping
2020/02/20 19:03:15 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/02/20 19:03:15 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/02/20 19:03:15 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2020/02/20 19:03:15 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 471
2020/02/20 19:03:15 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/02/20 19:03:15 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/02/20 19:03:15 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
Error: [GET /deployment/api/deployments/{depId}][200] getDeploymentByIdUsingGETOK  &{BlueprintID:38896c13-a57a-4c58-a5dd-ff66ce7f4f2b BlueprintVersion: CatalogItemID: CatalogItemVersion: CreatedAt:2020-02-20T22:07:32.605Z CreatedBy:mdittb638 Description: Expense:<nil> IconID: ID:7ca7540b-b5fc-4a32-a6d1-141f7cb17f9d Inputs:map[inCMI:Cloud-init inCount:75 inFlavor:4cpu-16Gb inITRC:test123 inIpv:IPv6 inLicense:rhat inRail:public inTags:mike:new inTenant:OneCloud vmName:md-demo1] LastRequest:0xc0006290e0 LastUpdatedAt:2020-02-21T00:01:44.744Z LastUpdatedBy:tango-blueprint-FXQgOCfpgDDR8tET LeaseExpireAt:0001-01-01T00:00:00.000Z Name:0xc00060a5a0 OrgID:9032098a-52e4-49a1-aa35-3eb11845413e Project:<nil> ProjectID:9683a1f4-2f27-424a-bf4b-09e41d9a4bcd Resources:[] Status:UPDATE_FAILED}
  on main.tf line 17, in resource "vra_deployment" "this":
  17: resource "vra_deployment" "this" {


When we check in vra its get the error message that you need x number of IPs and 0 are available.  That message isnt passed in terraform so the use only know if they are in vra.

**Comment by dark2phoenix** [comment]
dmettem is there something else we can provide you for this?

**Comment by dmettem** [comment]
No @dark2phoenix! I understood the ask. I'll include this and few other bugs in the current/upcoming sprint. Thanks!

**Comment by dmettem** [comment]
Btw, Thanks for more details @dark2phoenix, @mdittbrenner215!

**Comment by dmettem** [comment]
@dark2phoenix This is fixed in [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9) for most errors. Let me know if you come across any failures but don't see the message in the error when debug is not enabled.

**Comment by dmettem** [comment]
@dark2phoenix Did you happen to verify this? I'm closing the issue for now. Feel free to reopen if you come across any errors where the message is not seen unless run in debug mode.

**Comment by dark2phoenix** [comment]
It's in my plan to test this week.  Will comment and optionally re-open when I'm done.

**Comment by dark2phoenix** [comment]
Deepak all our tests came back positive.  Since 0.19 we are now seeing meaningful error messages.  Thank you for resolving this!

**Comment by dmettem** [comment]
@dark2phoenix - Thanks for the update!
