### ISSUE TITLE
Access Token Expiry and Cloud Assembly

### ISSUE THREAD

**Issue by nlitchfield** [vmware/terraform-provider-vra#165]
Apologies if this is the wrong location for this query. I'm hoping to use the terraform provider as a mechanism for provisioning Cloud Assembly blueprints on the VMWare Cloud. Per https://vdc-repo.vmware.com/vmwb-repository/dcr-public/44f35ac2-0f4c-4e9e-ac62-5587c2d9031c/0978a5ce-8337-41b8-b917-0512d22d5557/GUID-6ECB9373-58B9-4DFC-9A93-351E14AAD994.html the API (access?) token expires after 30 mins. 

If, which is to say when :(, my blueprint takes longer than 30 mins to deploy then terraform errors out on the next call to check the status of the deployment. If I'm calling the rest API directly, then I can just request a new access token, but the provider doesn't seem to support this. 

I guess my questions are: 

1. Am I missing something obvious - the most likely explanation. 
2. Are there plans to support a customizable duration for access tokens? I accept this might be a question for another team at VMWare.

**Comment by dmettem** [comment]
@nlitchfield - If the `access_token` is obtained from `/iaas/api/login`, the token gets renewed if it expires while the deployment request is going on.

Alternatively, you can use `refresh_token` in the provider instead of `access_token` which internally uses the `/iaas/api/login` to obtain the access token.

Hope this helps.

**Comment by dmettem** [comment]
Closing the issue. Feel free to re-open in case of additional questions.
