### ISSUE TITLE
do you have to be cloud assembly admin to request a blueprint deployment?

### ISSUE THREAD

**Issue by magnusstrandberg1** [vmware/terraform-provider-vra#191]
Hi, we want a user to be able to request services using the provider, but we see that it doesn't work without having admin rights in Cloud Assembly? Is this correct? It looks like it wants to list all projects and it doesn't work when just a "Service Broker user" or even user rights i Cloud Assembly?

Anyone seen this issue?

**Comment by codylcarlson** [comment]
I did some review of this and the problem is in how we provide the project.id value.  If you are not a Cloud Assembly Admin you cannot perform a Project ID lookup.  If you were to use a Cloud Admin during your 'terraform plan' you'll find the collected Project ID.  You could then hard code that ID into your .tf instead of performing a look up.  

From the product side we should allow project id lookups against any projects a user belongs to.

Hope that helps!

**Comment by dmettem** [comment]
@magnusstrandberg1 Can you please share the Terraform config file and also the roles the refresh token has with respect to Organization, Cloud Assembly, Service Broker, and Project level?

**Comment by magnusstrandberg1** [comment]
Hi, the role of the user is:
project: admin
organization member with service broker user role only

I will need to get the config file from a colleague.

**Comment by bortek** [comment]
Hi guys. terraform config file we use is basically the same as described in #170 with the addition of 

project_id = var.project_id_uuid

that I now explicitly set in the terraform tfvars file to a UUID of the project id. All the rest is more or less the same. 

The error I got when running terraform apply was one of these 

2020/05/12 07:40:02 [ERROR] <root>: eval: *terraform.EvalReadData, err: [GET /iaas/api/projects][403] getProjectsForbidden 
2020/05/12 07:40:02 [ERROR] <root>: eval: *terraform.EvalSequence, err: [GET /iaas/api/projects][403] getProjectsForbidden 
2020-05-12T07:40:02.476Z [DEBUG] plugin.terraform-provider-vra: 2020/05/12 07:40:02 Finished reading the vra_deployment resource with name lab01.compute-2
[31m
[1m[31mError: [0m[0m[1m[GET /iaas/api/projects][403] getProjectsForbidden [0m

**Comment by dmettem** [comment]
Due to underlying IaaS API limitations, a user with following permissions does not have access to project resource and data source.

Organization: Member
Service Roles: Service Broker user role only
Project: Administrator

Hence is the error:
> Error: [GET /iaas/api/projects][403] getProjectsForbidden

However, a Service Broker user can request a deployment by providing `project_id` instead of looking up for project id by its name.

```
resource "vra_deployment" "this" {
  name = var.deployment_name

  catalog_item_id          = data.vra_catalog_item.this.id
  catalog_item_version = var.catalog_item_version

  project_id = "a9b21d84-7ab0-48f6-8e79-7bae05527b17"
}
```

Hope this helps.

**Comment by bortek** [comment]
Can we change anything in these access right to get it work or you mean that it wont work regardless of what permissions we try? If so then the only way is left to be a cloud assembly admin, is that what you mean?

Organization: Member
Service Roles: Service Broker user role only
Project: Administrator

**Comment by dmettem** [comment]
Adding the "Cloud Assembly Viewer" role to the following permissions makes the project lookup (data source) work. Not sure if this option works for you..

Organization: Member
Service Roles: Service Broker user role only
Project: Administrator

I'll follow up internally on the plans to make the project lookup work for Service Broker user role.

**Comment by magnusstrandberg1** [comment]
Hi, yes that works! Thanks

**Comment by dmettem** [comment]
Glad to hear that.
I'm tracking an internal issue to support Project look up for Service Broker user role and will update here when it is supported.
