### ISSUE TITLE
Deploy multiple VMs with terraform

### ISSUE THREAD

**Issue by diggnsaegg** [vmware/terraform-provider-vra#218]
vRA version
8.1.0.9326 (15986821)
Terraform version
0.12.28
terraform-provider-vra plugin version
0.2.3

**Is your feature request related to a problem? Please describe.**
In the terraform provider for vra7 there was a way to deploy multiple VMs at once with the "deployment_count" variable, though you can set it in the terraform file but it is ignored

**Describe the solution you'd like**
a way to setup multiple vms at once, e.g. with the deployment_count variable

**Describe alternatives you've considered**
none, maybe there is already a variable for this I've not found yet? :)

**Comment by dmettem** [comment]
Hi @diggnsaegg,

Please provide your terraform configuration to understand the ask better.

Can you confirm if you are trying to deploy multiple VMs using `vra_machine` resource or `vra_deployment` resource? For both these resources, you can use in TF `count` argument to request multiple instances of the resource.

For `vra_deployment` resource, try to parameterize the deployment name so that it is different for each deployment requested when count is > 1.

You may also have a vRA blueprint with compute resource count property mapped to inputs via expression binding and give the number of VMs you want to deploy in a single deployment.

Thanks,
Deepak

**Comment by diggnsaegg** [comment]
This worked as expected. I thought the new vra provider would have it's own deployment counter like in vra7.
Thanks for the help!
