### ISSUE TITLE
fabric networks as an importable resource? 

### ISSUE THREAD

**Issue by cars** [vmware/terraform-provider-vra#224]
@dmettem @markpeek @Prativa20 
This is somewhat related to #223. I'd like to be able to manage the settings on fabric networks CIDR info, dns settings, tags etc. However the vRA API  doesn't currently provide any way to create fabric-networks (which makes some sense). This kinds of breaks the model for TF resources. That being said I'm wondering if there are feelings one way or another about possibly adding them as a importable resource so that the settings I mentioned earlier could be managed. 

This would mean TF wouldn't really "create" or "delete" them but they could be managed along with other vRA items rather than having to add in some other tooling/script to do so. 

-CRT

**Comment by hadrouj** [comment]
I have a customer looking to add tags on network fabrics using vra Terraform provider. 
They have hundreds of network fabrics and planning to add 2 tags on each network, so managing tags on networks would be a tedious task if done manually. that's why I think it would be a very useful addition to vra provider.
it would useful for environment initialisation but above all to detect any missing tags on networks and correct the drift. Thank you !

**Comment by dmettem** [comment]
It appears to be there is a lot interest for importable-only resources that doesn't allow create. Has anyone come across such importable-only resources from other providers?

I suppose, the `terraform apply` should fail during `create` as these are importable-only resources, and `terraform destroy` should silently remove the state without performing any remote operation. This seems to be simple workflow rather than forcing the users to use `terraform state rm` to explicitly remove them from state file as they cannot be destroyed anyways.

Any thoughts?

**Comment by cars** [comment]
Resolver in #251
