### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by mdb** [vmware/terraform-provider-vra#73]
Thanks for open sourcing `terraform-provider-vra`!

I see there is a `website` directory within which are Terraform-style documentation `.md` files. However, many of these files are empty. As a potential user of `terraform-provider-vra`, it would be very useful to be able to read provider documentation.

Thanks!

**Comment by markpeek** [comment]
Thank you @mdb for the feedback. Yes, we decided to make the project open source before having all of the documentation written in order to give early access to people asking about this provider. We are in the process of working through the resources and data sources adding docs. I'll leave this open to track the progress of this work.

**Comment by aleksejlopasov** [comment]
Any updates? It's quite hard to use resources when you don't know the full list of required and optional fields and their meanings

**Comment by tenthirtyam** [comment]
Isn't this now [covered here](https://registry.terraform.io/providers/vmware/vra/latest/docs) and thus can be closed?
